name: IOOS
channels:
  - conda-forge
dependencies:
  - python=3.11
  - bagit
  - bokeh
  - cartopy
  - cc-plugin-glider
  - cc-plugin-ncei
  - cf_xarray
  - cftime
  - compliance-checker
  - descartes
  - easyargs
  - erddapy
  - flake8
  - folium
  - geojson
  - geojsonio
  - geolinks
  - geopandas
  - gridgeo
  - hvplot
  - ioos-tools
  - ioos_qc
  - ipyleaflet
  - joblib
  - jupyter
  - jupyter-book >=0.12.1
  - matplotlib-base
  - nbdime
  - nbval
  - nc-time-axis
  - nco
  - oceans
  - oct2py
  - odvc
  - palettable
  - phantomjs
  - pocean-core
  - pre-commit
  - pyoos
  - pyresample
  - pysgrid
  - pytest
  - pyugrid
  - pyworms
  - rasterio
  - seaborn
  - selenium
  - sensorml2iso
  - simplekml
  - siphon
  - sympy
  - thredds_crawler
  - tqdm
  - utide
  - windrose
  - xarray
  - xlrd
  - xmltodict
