name: IOOS
channels:
  - conda-forge
dependencies:
  - python=3.12
  - bagit
  - bokeh
  - cartopy
  - cc-plugin-glider
  - cc-plugin-ncei
  - cf_xarray
  - cftime
  - ckanapi
  - compliance-checker
  - dask
  - descartes
  - easyargs
  - erddapy
  - flake8
  - folium
  - geodatasets
  - geojson
  - geojsonio
  - geolinks
  - geopandas
  - geoplot
  - gliderpy
  - gridgeo
  - humanize
  - hvplot
  - intake
  - ioos_qc
  - ioos-metrics
  - ipyleaflet
  - joblib
  - jupyter
  - jupyter-book >=0.12.1
  - jupyterlab
  - matplotlib-base
  - nbclassic
  - nbdime
  - nbval
  - nc-time-axis
  - nco
  - oceans
  - oct2py
  - odvc
  - openpyxl
  - palettable
  - phantomjs
  - pocean-core >=3.1
  - pre-commit
  - pyarrow
  - pyobis
  - pyoos
  - pyresample
  - pysgrid
  - pytest
  - pyugrid
  - pyworms
  - rasterio
  - seaborn
  - selenium
  - sensorml2iso
  - simplekml
  - siphon
  - sympy
  - tabulate
  - thredds_crawler
  - tqdm
  - utide
  - windrose
  - xarray
  - xmltodict
  - zarr
  # R packages.
  - rpy2
  - r-base=4
  - r-dplyr
  - r-dt
  - r-finch
  - r-ggfortify
  - r-ggplot2
  - r-gsw
  - r-htmlwidgets
  - r-httr
  - r-irkernel
  - r-lubridate
  - r-mapdata
  - r-ncdf4
  - r-obistools
  - r-oce
  - r-rcolorbrewer
  - r-readr
  - r-rerddap
  - r-reshape2
  - r-robis>=2.3.9
  - r-sp
  - r-xtractomatic
  - r-xts
platforms:
  - linux-64
  - osx-64
  - win-64
