name: IOOS
channels:
  - conda-forge
dependencies:
  - python=3.13
  - bokeh
  - cartopy
  - cf-units
  - cf-xarray
  - ckanapi
  - compliance-checker
  - erddapy
  - folium
  - gdal
  - geopandas
  - geoplot
  - gliderpy>=0.3.1
  - gridgeo
  - humanize
  - ioos-metrics
  - ioos-qc
  - ipyleaflet
  - ipywidgets
  - jupyter
  - lxml
  - matplotlib-base
  - nbclassic
  - netcdf4
  - numpy
  - oceans
  - odvc
  - owslib
  - palettable
  - pandas
  - pocean-core
  - pyobis
  - pysgrid
  - pyugrid
  - pyworms
  - requests
  - retrying
  - seawater
  - shapely
  - stamina
  - tqdm
  - xarray
  - zarr
platforms:
  - linux-64
  - osx-64
  - osx-arm64
  - win-64
